In [2]:
#question1
import numpy as np
def saisie():
    column=int(input("insert the number of your array column: "))
    row=int(input("insert the number of rows : "))
    while column<=0 or row<=0 :
        column=int(input("insert the number of your array column: "))
        row=int(input("insert the number of rows : "))
    list_array=[]
    for i in range (row):
        list_column=[]
        for x in range (column):
            element=input("insert an item :")
            list_column.append(element)
        list_array.append(list_column)
    array_out=np.array(list_array)
    return array_out
a=saisie()
print("your array is: ",a)
list_arr=a.tolist()
print("the list of your array: ",list_arr)

insert the number of your array column: 3
insert the number of rows : 2
insert an item :5
insert an item :4
insert an item :7
insert an item :9
insert an item :2
insert an item :1
your array is:  [['5' '4' '7']
 ['9' '2' '1']]
the list of your array:  [['5', '4', '7'], ['9', '2', '1']]


In [5]:
#question2
import numpy as np
def saisie():
    column=int(input("insert the number of your array column: "))
    row=int(input("insert the number of rows : "))
    while column<=0 or row<=0 :
        column=int(input("insert the number of your array column: "))
        row=int(input("insert the number of rows : "))
    list_array=[]
    for i in range (row):
        list_column=[]
        for x in range (column):
            element=int(input("insert an item :"))
            list_column.append(element)
        list_array.append(list_column)
    array_out=np.array(list_array)
    return array_out
a=saisie()
print("your array is: ",a)
t=a.trace()
print("the diagonal total is: ",t)

insert the number of your array column: 3
insert the number of rows : 3
insert an item :5
insert an item :4
insert an item :7
insert an item :1
insert an item :0
insert an item :8
insert an item :55
insert an item :5
insert an item :5
your array is:  [[ 5  4  7]
 [ 1  0  8]
 [55  5  5]]
the diagonal total is:  10


In [21]:
#question3
import numpy as np
def saisie():
    column=int(input("insert the number of your array column: "))
    row=int(input("insert the number of rows : "))
    while column<=0 or row<=0 :
        column=int(input("insert the number of your array column: "))
        row=int(input("insert the number of rows : "))
    list_array=[]
    for i in range (row):
        list_column=[]
        for x in range (column):
            element=float(input("insert an item :"))
            list_column.append(element)
        list_array.append(list_column)
    array_out=np.array(list_array)
    return array_out
def higher(array_higher,limit):
    shape_array=array_higher.shape
    elements_higher=""
    for i in range(shape_array[0]):
        for x in range(shape_array[1]):
            if array_higher[i,x]>limit :
                if elements_higher=="":
                    elements_higher=str(array_higher[i,x])
                else:
                    elements_higher=elements_higher+","+str(array_higher[i,x])
    return elements_higher
a=saisie()
print("your array is: ",a)
X=float(input("insert a value to compare : "))
b=higher(a,X)
print("the elements higher than",X,"in your array are : ",b)


insert the number of your array column: 3
insert the number of rows : 3
insert an item :1.2
insert an item :5
insert an item :8.5
insert an item :2.9
insert an item :7
insert an item :6
insert an item :45
insert an item :22.2
insert an item :42.89654
your array is:  [[ 1.2      5.       8.5    ]
 [ 2.9      7.       6.     ]
 [45.      22.2     42.89654]]
insert a value to compare : 4
the elements higher than 4.0 in your array are :  5.0,8.5,7.0,6.0,45.0,22.2,42.89654


In [24]:
#question4
import numpy as np
def saisie():
    column=int(input("insert the number of your array column: "))
    row=int(input("insert the number of rows : "))
    while column<=0 or row<=0 :
        column=int(input("insert the number of your array column: "))
        row=int(input("insert the number of rows : "))
    list1_array=[]
    for i in range (row):
        list1_column=[]
        for x in range (column):
            element1=float(input("insert an item in your 1st array :"))
            list1_column.append(element1)
        list1_array.append(list1_column)
    array1_out=np.array(list1_array)
    list2_array=[]
    for i in range (row):
        list2_column=[]
        for x in range (column):
            element2=float(input("insert an item in your 2nd array :"))
            list2_column.append(element2)
        list2_array.append(list2_column)
    array2_out=np.array(list2_array)
    return array1_out,array2_out
def sum_array(array1,array2):
    shape_array=array1.shape
    array_sum=np.zeros(shape=(shape_array[0],shape_array[1]))
    for i in range(shape_array[0]):
        for x in range(shape_array[1]):
            array_sum[i,x]=array1[i,x]+array2[i,x]
    return array_sum
A,B=saisie()
print("your 1st array is",A)
print("your 2nd array is",B)
t=sum_array(A,B)
print("your sum array is",t)

insert the number of your array column: 2
insert the number of rows : 2
insert an item in your 1st array :1
insert an item in your 1st array :2.2
insert an item in your 1st array :5
insert an item in your 1st array :4
insert an item in your 2nd array :10
insert an item in your 2nd array :7
insert an item in your 2nd array :2
insert an item in your 2nd array :1
your 1st array is [[1.  2.2]
 [5.  4. ]]
your 2nd array is [[10.  7.]
 [ 2.  1.]]
your sum array is [[11.   9.2]
 [ 7.   5. ]]


In [37]:
#question5
import numpy as np
def saisie():
    column=int(input("insert the number of your array column: "))
    row=int(input("insert the number of rows : "))
    while column<=0 or row<=0 :
        column=int(input("insert the number of your array column: "))
        row=int(input("insert the number of rows : "))
    list_array=[]
    for i in range (row):
        list_column=[]
        for x in range (column):
            element=float(input("insert an item :"))
            list_column.append(element)
        list_array.append(list_column)
    array_out=np.array(list_array)
    return array_out
def mean_substract(array_mean):
    shape_array=array_mean.shape
    mean_values=np.mean(array_mean,axis=1)
    list_mean=mean_values.tolist()
    arraysub_out=np.zeros(shape=shape_array)
    for i in range(shape_array[0]):
        l=list_mean[i]
        for x in range(shape_array[1]):
            arraysub_out[i,x]=array_mean[i,x]-l
    return arraysub_out           
a=saisie()
print("your array is: ",a)
t=mean_substract(a)
print ("this is your new array :",t)

insert the number of your array column: 3
insert the number of rows : 3
insert an item :2
insert an item :1
insert an item :5
insert an item :6
insert an item :4
insert an item :7
insert an item :3
insert an item :1
insert an item :9
your array is:  [[2. 1. 5.]
 [6. 4. 7.]
 [3. 1. 9.]]
[2.6666666666666665, 5.666666666666667, 4.333333333333333]
this is your new array : [[-0.66666667 -1.66666667  2.33333333]
 [ 0.33333333 -1.66666667  1.33333333]
 [-1.33333333 -3.33333333  4.66666667]]
